### ISSUE TITLE
Not working at all

### ISSUE THREAD

**Issue by NixonOK** [Shashank02051997/FancyGifDialog-Android#10]
ClassCastException: android.graphics.drawable.RippleDrawable cannot be cast to android.graphics.drawable.GradientDrawable

Used the library in this project for almost 6 months now, really appreciate you, please fix this :) 

 2019-07-10 08:45:02.070 28829-28829/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.jitunInc.jitun, PID: 28829
    java.lang.RuntimeException: Unable to start activity ComponentInfo{com.jitunInc.jitun/com.jitunInc.jitun.Activity.JitunHomeActivity}: java.lang.ClassCastException: android.graphics.drawable.RippleDrawable cannot be cast to android.graphics.drawable.GradientDrawable
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3037)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3172)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1906)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6863)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:537)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
     Caused by: java.lang.ClassCastException: android.graphics.drawable.RippleDrawable cannot be cast to android.graphics.drawable.GradientDrawable
        at c.e.a.a.c$a.a(Unknown Source:106)
        at com.jitunInc.jitun.Activity.JitunHomeActivity.onCreate(Unknown Source:354)
        at android.app.Activity.performCreate(Activity.java:7149)
        at android.app.Activity.performCreate(Activity.java:7140)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1288)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3017)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3172) 
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78) 
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1906) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:193) 
        at android.app.ActivityThread.main(ActivityThread.java:6863) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:537) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858) 
2019-07-10 08:45:02.105 562-562/? E/SELinux: avc:  denied  { find } for service=opdiagnose pid=28829 uid=10586 scontext=u:r:untrusted_app:s0:c74,c258,c512,c768 tcontext=u:object_r:opdiagnose_service:s0 tclass=service_manager permissive=0
2019-07-10 08:45:02.105 562-562/? E/SELinux: avc:  denied  { find } for service=opdiagnose pid=28829 uid=10586 scontext=u:r:untrusted_app:s0:c74,c258,c512,c768 tcontext=u:object_r:opdiagnose_service:s0 tclass=service_manager permissive=0
2019-07-10 08:45:02.162 885-1495/? E/InputDispatcher: channel '4669927 com.jitunInc.jitun/com.jitunInc.jitun.Activity.SplashActivity (server)' ~ Channel is unrecoverably broken and will be disposed!
2019-07-10 08:45:02.172 885-2775/? E/ActivityTrigger: activityResumeTrigger: not whiteListedcom.teslacoilsw.launcher/com.teslacoilsw.launcher.NovaLauncher/61161
2019-07-10 08:45:02.343 885-3002/? E/JobScheduler: jobid:20536
    java.lang.IllegalStateException: Same jobid in systemuid.
        at com.android.server.job.JobSchedulerService.scheduleAsPackage(JobSchedulerService.java:888)
        at com.android.server.job.JobSchedulerService$JobSchedulerStub.schedule(JobSchedulerService.java:2592)
        at android.app.JobSchedulerImpl.schedule(JobSchedulerImpl.java:44)
        at com.android.server.backup.FullBackupJob.schedule(FullBackupJob.java:54)
        at com.android.server.backup.BackupManagerService$3.run(BackupManagerService.java:1925)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:193)
        at android.os.HandlerThread.run(HandlerThread.java:65)

**Comment by rajextreme9476** [comment]
Same error i got
